---
version: '3'

services:
  eta-to-notification:
    image: eta-to-notification
    container_name: eta-to-notification
    build:
      context: .
      dockerfile: Dockerfile
      target: main-image
    # networks: 
    #   - default
    ports:
      - "8010:8010"
      - "4440:4440"
    env_file: ./eta_to_notification.env
    #network_mode: host

    # networks: 
    #   default: 
    #     external: true
    #     name: confluent_default
