---

services:
  eta_calculator:
    image: eta_calculator
    container_name: eta-calculator
    build:
      context: .
      dockerfile: Dockerfile
      target: main-image

    ports:
      - "8010:8010"
    env_file: ./eta_calculator.env
